## MOVIE  RECOMMENDATION SYSTEM

Use of each dataset:
1. movies.csv - Metadata for Content-Based Filtering. 
2. rating.csv - Core data for Collaborative Filtering. 
3. tags.csv - User Tags.
4. links.csv - Links to fetch posters/synopses via the TMDB API later.

In [10]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [11]:
movies = pd.read_csv(r'C:\Abhishree\Projects_GitHubLinked\Movie Recommender\data\ml-latest-small\movies.csv')
ratings = pd.read_csv(r'C:\Abhishree\Projects_GitHubLinked\Movie Recommender\data\ml-latest-small\ratings.csv')

In [12]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [13]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [14]:
movies.columns

Index(['movieId', 'title', 'genres'], dtype='str')

In [15]:
ratings.columns

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='str')

In [16]:
movies['genres'].value_counts()

genres
Drama                                     1053
Comedy                                     946
Comedy|Drama                               435
Comedy|Romance                             363
Drama|Romance                              349
                                          ...
Adventure|Mystery|Sci-Fi|Thriller            1
Action|Comedy|Crime|Horror                   1
Action|Adventure|Children|Sci-Fi             1
Action|Adventure|Comedy|Fantasy|Sci-Fi       1
Action|Animation|Comedy|Fantasy              1
Name: count, Length: 951, dtype: int64

## one hot encode of genres.

In [17]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

## CONTENT BASED RECOMMENDATION

1. convert words/features to numbers(vectors) and then compare the angle between them.
STEP A: TF-IDF
* It converts text into numerical vectors based on how important a word is to a document relative to all documents.
* TF-IDF(t, d, D) = TF(t, d)*IDF(t, D)
* TF (Term Frequency): How often a word appears in a single item description.
* IDF (Inverse Document Frequency): Penalizes common words (like "the", "movie", "a") that appear across every item.

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
paragraph = ["A recommender system, also called a recommendation algorithm, "
"recommendation engine, recommendation platform, or in the context of social "
"media, simply algorithm is a type of information filtering system that suggests "
"items most relevant to a particular user."]
v = TfidfVectorizer()
transformed_output = v.fit_transform(paragraph)
print(v.vocabulary_)

{'recommender': 17, 'system': 22, 'also': 1, 'called': 2, 'recommendation': 16, 'algorithm': 0, 'engine': 4, 'platform': 15, 'or': 13, 'in': 6, 'the': 24, 'context': 3, 'of': 12, 'social': 20, 'media': 10, 'simply': 19, 'is': 8, 'type': 26, 'information': 7, 'filtering': 5, 'that': 23, 'suggests': 21, 'items': 9, 'most': 11, 'relevant': 18, 'to': 25, 'particular': 14, 'user': 27}

### IDF SCORE:

In [31]:
all_feature_names = v.get_feature_names_out()
for word in all_feature_names:
    idx = v.vocabulary_.get(word)
    print(f"{word} {v.idf_[idx]}")

algorithm 1.0
also 1.0
called 1.0
context 1.0
engine 1.0
filtering 1.0
in 1.0
information 1.0
is 1.0
items 1.0
media 1.0
most 1.0
of 1.0
or 1.0
particular 1.0
platform 1.0
recommendation 1.0
recommender 1.0
relevant 1.0
simply 1.0
social 1.0
suggests 1.0
system 1.0
that 1.0
the 1.0
to 1.0
type 1.0
user 1.0

In [32]:
paragraph[:2]

['A recommender system, also called a recommendation algorithm, recommendation engine, recommendation platform, or in the context of social media, simply algorithm is a type of information filtering system that suggests items most relevant to a particular user.']

In [34]:
transformed_output.toarray()[:2]

array([[0.2981424, 0.1490712, 0.1490712, 0.1490712, 0.1490712, 0.1490712,
        0.1490712, 0.1490712, 0.1490712, 0.1490712, 0.1490712, 0.1490712,
        0.2981424, 0.1490712, 0.1490712, 0.1490712, 0.4472136, 0.1490712,
        0.1490712, 0.1490712, 0.1490712, 0.1490712, 0.2981424, 0.1490712,
        0.1490712, 0.1490712, 0.1490712, 0.1490712]])